name: Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - .docs/**
      - ElevenLabs-DotNet/**
      - ElevenLabs-DotNet-Proxy/**
  pull_request:
    branches:
      - '*'
    paths:
      - .docs/**
      - ElevenLabs-DotNet/**
      - ElevenLabs-DotNet-Proxy/**
    types:
      - opened
      - synchronize

  workflow_dispatch:
    inputs:
      dotnet-version:
        description: ".NET version to use"
        required: false
        default: "8.x"

permissions:
  contents: read
  pages: write
  checks: write
  id-token: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  DOTNET_VERSION: ${{ github.event.inputs.dotnet-version || '8.x' }}

jobs:
  build:
    if: ${{ !github.event_name == 'pull_request' || !github.event.pull_request.draft }}
    env:
      PACKAGE_VERSION: ''
      COVERAGE_FILE_PATH: ''
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - run: dotnet restore

    - run: dotnet build --configuration Release --no-restore

    - name: Test Packages
      if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'push' }}
      run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --logger:trx --no-build --no-restore --results-directory ./test-results
      env:
        ELEVEN_LABS_API_KEY: ${{ secrets.ELEVEN_LABS_API_KEY }}

    - name: Publish Test Results
      if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'push' && always() }}
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: test-results/**/*.trx
        comment_mode: off
        report_individual_runs: true
        compare_to_earlier_commit: false

    - name: Determine Coverage File Path
      if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'push' && always() }}
      shell: bash
      run: |
        COVERAGE_FILE_PATH=$(find ./test-results -name 'coverage.cobertura.xml' | head -n 1)
        echo "COVERAGE_FILE_PATH=$COVERAGE_FILE_PATH" >> $GITHUB_ENV

    - name: Code Coverage Summary Report
      if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'push' && always() }}
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ env.COVERAGE_FILE_PATH }}
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Write Coverage Job Summary
      if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'push' && always() }}
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

    - name: Pack and Publish NuGet Package
      run: |
        $projectPath = "${{ github.workspace }}\ElevenLabs-DotNet"
        $proxyProjectPath = "${{ github.workspace }}\ElevenLabs-DotNet-Proxy"

        # pack ElevenLabs-DotNet
        dotnet pack $projectPath --configuration Release --include-symbols
        $out = "$projectPath\bin\Release"
        $packagePath = Get-ChildItem -Path $out -File -Include '*.nupkg' -Exclude '*symbols*' -Recurse -ErrorAction SilentlyContinue

        if ($packagePath) {
          Write-Host Package path: $packagePath
        } else {
          Write-Host Failed to find package at $out
          exit 1
        }

        # pack ElevenLabs-DotNet-Proxy
        dotnet pack $proxyProjectPath --configuration Release --include-symbols
        $proxyOut = "$proxyProjectPath\bin\Release"
        $proxyPackagePath = Get-ChildItem -Path $proxyOut -File -Include '*.nupkg' -Exclude '*symbols*' -Recurse -ErrorAction SilentlyContinue

        if ($proxyPackagePath) {
          Write-Host Package path: $proxyPackagePath
        } else {
          Write-Host Failed to find package at $proxyOut
          exit 1
        }

        $isRelease = "${{ github.ref == 'refs/heads/main' }}"

        if ($isRelease -eq 'true') {
          dotnet nuget push $packagePath.FullName --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push $proxyPackagePath.FullName --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        }

        $version = $packagePath.Name -replace "^ElevenLabs-DotNet.(.*).nupkg$",'$1'
        echo "PACKAGE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ElevenLabs-DotNet.${{ env.PACKAGE_VERSION }}
        path: |
          ${{ github.workspace }}/ElevenLabs-DotNet/bin/Release/ElevenLabs-DotNet.${{ env.PACKAGE_VERSION }}.nupkg
          ${{ github.workspace }}/ElevenLabs-DotNet/bin/Release/ElevenLabs-DotNet.${{ env.PACKAGE_VERSION }}.symbols.nupkg
          ${{ github.workspace }}/ElevenLabs-DotNet/bin/Release/ElevenLabs-DotNet-Proxy.${{ env.PACKAGE_VERSION }}.nupkg
          ${{ github.workspace }}/ElevenLabs-DotNet/bin/Release/ElevenLabs-DotNet-Proxy.${{ env.PACKAGE_VERSION }}.symbols.nupkg
        if-no-files-found: ignore

  docs:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: build docfx
      run: |
        dotnet tool update -g docfx
        docfx .docs/docfx.json

    - uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4.0.3
